### ISSUE TITLE
Something weird

### ISSUE THREAD

**Issue by stefjoosten** [AmpersandTarski/Publications#1]
@sjcjoosten, 
I have something weird, on which I'd like your opinion.

In the proof of lemma largest_delta_s (see below) I have made a mistake when applying `defDelta`. I mixed up the union and the minus.
Nevertheless, Isabelle is quite happy with the result.
Can you explain that? It seems to me that this proof cannot be correct...
(Notice that the proof of lemma 47 is almost the same, but it does not contain the "mistake". It too is considered correct by Isabelle .)

Stef
![afbeelding](https://user-images.githubusercontent.com/275768/28420186-975962ae-6d61-11e7-85a8-7b9d2bed7292.png)

# Reproducing the error
Look at file Increment.thy in AmpersandTarski/Publications@d3fe05508797bb6ac711d340c635f03abeb0bab6.

**Comment by sjcjoosten** [comment]
My guess is that "show ?thesis using assms by auto" is enough to prove the theorem, and you may use something irrelevant to prove it.
